### PR TITLE
Updated gradle to 7.0.2, jdk to 11

### PR DESCRIPTION
**Pull request by tunix**
Could you also do the following please?

* Create a new branch `v6.x` from master branch
* Create `v6.x` track on snapcraft.io and integrate `v6.x` branch with this new track
* All master builds will continue to go into edge track as usual (and I'll promote it to stable once builds are complete)

### CODE REVIEW

**Comment by tunix** [comment]
12 days.. and counting... 😞

**Comment by om26er** [comment]
>     * Create `v6.x` track on snapcraft.io and integrate `v6.x` branch with this new track

This request would have to be made on the forum but I guess let's first wait for the new branch to get created.

**Comment by tunix** [comment]
> > ```
> > * Create `v6.x` track on snapcraft.io and integrate `v6.x` branch with this new track
> > ```
> 
> This request would have to be made on the forum but I guess let's first wait for the new branch to get created.

I didn't know that. 🤔  Is there a reason for making branching requests on the forum? Is it because the snap belongs to Snapcrafters?

**Comment by igorljubuncic** [comment]
Do you expect any major breakages in workflows btw? Anything for users to be aware of if they need to switch to this proposed track?

**Comment by tunix** [comment]
@igorljubuncic - nope. it's just a maintenance track. 6.8.x will probably get security updates etc. so I want to make sure that it still exists.

**Comment by igorljubuncic** [comment]
OK, let's do the following - can you create a forum post asking for a new track creation, tag me please so I can +1 it. Then, we can build and push this to that track. Which one should be the default one btw (6.x or 7.x)?

**Comment by tunix** [comment]
@igorljubuncic - 7.x should be default. I'm creating the forum thread now. Cheers!

**Comment by tunix** [comment]
@igorljubuncic - Now that the track is ready, how do we proceed? I was planning the following:

* master branch -> default track (7.x)
* 6.8.x branch -> 6.8.x track

**Comment by igorljubuncic** [comment]
Just for everyone's visibility, we're working on new ways to get more community involvement in Snapcrafters, so we'll come back with some interesting news very soon. Hence, a brief pause of this PR.

**Comment by tunix** [comment]
gradle 7.0.2 has been released. 🙄

**Review by igorljubuncic — APPROVED** [review]

**Pull request merged**
