### PR TITLE
Update snapcraft.yaml

### LINKED ISSUE #11: Snap does not update PATH variable which results in unusable snap
I installed gradle via snap, then installed Java 16 needed to build a project and removed Java 11. The problem is snap still points to nonexisting Java 11.

```
You are using an outdated version of Java (11). Java 16 or higher is required.
The JAVA_HOME environment variable is currently set to (/snap/gradle/101/usr/lib/jvm/default-java).
```

Tried removing and installing this snap again, `sudo systemctl restart snapd snapd.socket` and `sudo systemctl daemon-reload` with no luck.

### PR DESCRIPTION
**Pull request by diddledan**
* Bump java to 16

Fixes #11

### CODE REVIEW

**Comment by Lin-Buo-Ren** [comment]
LGTM.

**Review by tunix — APPROVED** [review]

**Comment by Lin-Buo-Ren** [comment]
According to https://github.com/snapcrafters/gradle/pull/12 Gradle seems to depend on the Java runtime the Java projects calling it relies on(instead of the version bundled in the snap, which means this fix doesn't seem to be the right solution to solve this problem (other projects targeting Java 11 may break?), maybe:

* Make the snap classic confinement
* Bundle all supported Java runtime that may be targeted, and switching it according to the project-targeted version
* Bundle the latest runtime version available (as long as backward compatibility is available).

**Comment by tunix** [comment]
The snap is already classic. It's able to work with any Java runtime.

**Comment by Lin-Buo-Ren** [comment]
> The snap is already classic. It's able to work with any Java runtime.

Sorry didn't notice that.

Then why do the issue occur if the Java runtime version isn't an issue?

**Comment by tunix** [comment]
I don't think there is an issue. :) The OP's project is compiled against Java 16 and that's probably why prints that message. I've JDK 8 and 11 installed on my system and gradle works fine with whatever project I throw at it. Since gradle works with JDK 8+, it should be fine to have the latest JDK inside the snap.

**Pull request merged**
